pushed to github but doesnt serve

diff --git a/.github/workflows/deploy_frontend.yml b/.github/workflows/deploy_frontend.yml
--- a/.github/workflows/deploy_frontend.yml
+++ b/.github/workflows/deploy_frontend.yml
@@ -22,7 +22,6 @@ jobs:
     # - name: Debug REACT_APP_API_URL
     #   shell: bash
     #   run: |
-    #     #env 
     #     echo -e "\e[32m@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\e[0m"
     #     echo -e "\e[32mREACT_APP_API_URL=${REACT_APP_API_URL}\e[0m"
     #     env
@@ -61,18 +60,11 @@ jobs:
         env
         echo -e "\e[32m$(pwd)\e[0m"
         npm run build || (echo -e "\e[31mBuild step failed.\e[0m" && exit 1)
-        # echo -e "\e[32mBuild completed. Checking build output:\e[0m"
-        # grep -r REACT_APP build || echo "No REACT_APP variables found in build output"
-        # grep -rho '"REACT_APP_[^"]*":"[^"]*"' build/ | \
-        #   sed -E 's/"([^"]+)":"([^"]+)"/\1=\2/' | \
-        #   awk '{print "\032[32m" $0 "\032[0m"}' || \
-        #   echo "No REACT_APP variables found in build output"
 
     - name: Deploy to GitHub Pages
       env:
-        GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
+        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
       run: |
-        echo GITHUB_REPOSITORY:${GITHUB_REPOSITORY}
         cd frontend/build
         git init
         git config user.name "github-actions[bot]"
@@ -81,33 +73,13 @@ jobs:
         git commit -m "Deploy frontend"
         git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:gh-pages
 
-    # - name: Setup Pages
-    #   uses: actions/configure-pages@v4
-    #   with:
-    #     token: ${{ secrets.GITHUB_TOKEN }}
+    - name: Build Succeeded
+      if: success()
+      run: echo -e "\e[32mBuild succeeded.\e[0m"
 
-    # - name: Upload artifact
-    #   uses: actions/upload-pages-artifact@v3
-    #   with:
-    #     path: './frontend/build'
-
-    # - name: Deploy to GitHub Pages
-    #   id: deployment
-    #   uses: actions/deploy-pages@v4
-
-    # - name: Check for API URL in built files
-    #   shell: bash
-    #   run: |
-    #     echo "Checking for API URL in built files:"
-    #     # grep -r "REACT_APP_API_URL" frontend/build || echo "REACT_APP_API_URL not found in build output"
-
-    # - name: Build Succeeded
-    #   if: success()
-    #   run: echo -e "\e[32mBuild succeeded.\e[0m"
-
-    # - name: Build Failed
-    #   if: failure()
-    #   shell: bash
-    #   run: |
-    #     echo -e "\e[31mBuild failed.\e[0m"
-    #     exit 1
+    - name: Build Failed
+      if: failure()
+      shell: bash
+      run: |
+        echo -e "\e[31mBuild failed.\e[0m"
+        exit 1
