solved why environment doesn't work (refered to it as secret and not as env)

diff --git a/.github/workflows/deploy_frontend.yml b/.github/workflows/deploy_frontend.yml
--- a/.github/workflows/deploy_frontend.yml
+++ b/.github/workflows/deploy_frontend.yml
@@ -39,7 +39,7 @@ jobs:
       shell: bash
       env:
         REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
-        REACT_APP_ENVIRONMENT: ${{ secrets.REACT_APP_ENVIRONMENT }}
+        REACT_APP_ENVIRONMENT: ${{ env.REACT_APP_ENVIRONMENT }}
       run: |
         echo -e "\e[31mREACT_APP_API_URL=${REACT_APP_API_URL}\e[0m"
         echo -e "\e[31mREACT_APP_ENVIRONMENT=${REACT_APP_ENVIRONMENT}\e[0m"
@@ -54,15 +54,15 @@ jobs:
       shell: bash
       env:
         REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
-        REACT_APP_ENVIRONMENT: ${{ secrets.REACT_APP_ENVIRONMENT }}
+        REACT_APP_ENVIRONMENT: ${{ env.REACT_APP_ENVIRONMENT }}
       run: |
         cd frontend
-        export REACT_APP_BUILD_TIME=$(date +'%Y-%m-%dT%H:%M:%S%z' -d 'TZ="America/Argentina/Buenos_Aires"')
+        export REACT_APP_BUILD_TIME=$(TZ=America/Argentina/Buenos_Aires date +"%Y-%m-%d %H:%M:%S")
         echo -e "\e[31mBuilding with environment variables:\e[0m"
-        # env | grep REACT_APP
-        npm run build || (echo -e "\e[31mBuild step failed.\e[0m" && exit 1)
+        env | grep REACT_APP
+        # npm run build || (echo -e "\e[31mBuild step failed.\e[0m" && exit 1)
         echo "Build completed. Checking build output:"
-        grep -r REACT_APP build || echo "No REACT_APP variables found in build output"
+        # grep -r REACT_APP build || echo "No REACT_APP variables found in build output"
 
     # - name: Setup Pages
     #   uses: actions/configure-pages@v4
