insta-fail in red

diff --git a/.github/workflows/deploy_frontend.yml b/.github/workflows/deploy_frontend.yml
--- a/.github/workflows/deploy_frontend.yml
+++ b/.github/workflows/deploy_frontend.yml
@@ -27,25 +27,35 @@ jobs:
         node-version: '20'
 
     - name: Install dependencies
+      shell: bash
       run: |
+        set -e
+        trap 'echo -e "\e[31mInstall dependencies step failed.\e[0m"' ERR
         cd frontend
         npm ci
 
-    - name: Print Secret Values
+    - name: Print Environment Variables and Secrets
+      shell: bash
       run: |
         echo -e "\e[31mREACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}\e[0m"
-        echo -e "\e[31mREACT_APP_ENVIRONMENT=${{ secrets.ENVIRONMENT }}\e[0m"
-        echo -e "\e[31mPUBLIC_URL=${{ secrets.PUBLIC_URL }}\e[0m"
-        echo -e "\e[31mGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}\e[0m"
+        echo -e "\e[31mREACT_APP_ENVIRONMENT=${{ secrets.REACT_APP_ENVIRONMENT }}\e[0m"
+        # Remove PUBLIC_URL if not needed
+        # echo -e "\e[31mPUBLIC_URL=${{ secrets.PUBLIC_URL }}\e[0m"
+        # Uncomment the following line to print GITHUB_TOKEN (not recommended)
+        # echo -e "\e[31mGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}\e[0m"
 
     - name: Build
-      run: |
-        cd frontend
-        npm run build
+      shell: bash
       env:
         REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
-        REACT_APP_ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
-        PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
+        REACT_APP_ENVIRONMENT: ${{ secrets.REACT_APP_ENVIRONMENT }}
+        # Remove PUBLIC_URL if not needed
+        # PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
+      run: |
+        set -e
+        trap 'echo -e "\e[31mBuild step failed.\e[0m"' ERR
+        cd frontend
+        npm run build
 
     - name: Setup Pages
       uses: actions/configure-pages@v4
@@ -60,3 +70,14 @@ jobs:
     - name: Deploy to GitHub Pages
       id: deployment
       uses: actions/deploy-pages@v4
+
+    # This step runs when any previous step fails
+    - name: Build Failed
+      if: failure()
+      run: echo -e "\e[31mBuild failed.\e[0m"
+      shell: bash
+
+    # This step runs when all previous steps succeed
+    - name: Build Succeeded
+      if: success()
+      run: echo "Build succeeded."
