installing gcloud cli to let the script continue

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -14,7 +14,7 @@ jobs:
     runs-on: ubuntu-latest
     defaults:
       run:
-        working-directory: ./backend  # Set the default working directory to backend
+        working-directory: ./backend
 
     steps:
     - uses: actions/checkout@v2
@@ -25,16 +25,26 @@ jobs:
       run: |
         echo "$GCP_SA_KEY" > .secrets
 
+    - name: Set up Cloud SDK
+      run: |
+        if ! command -v gcloud &> /dev/null
+        then
+          echo "gcloud could not be found, installing now"
+          # Install gcloud
+          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
+          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
+          sudo apt-get update && sudo apt-get install google-cloud-sdk
+        else
+          echo "gcloud is already installed"
+        fi
+        # Activate service account
+        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > /tmp/gcp-key.json
+        gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
+        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
+
     - name: Configure Docker to use GCloud credentials
       run: |
         gcloud auth configure-docker gcr.io --quiet
-
-    - name: Set up Cloud SDK
-      uses: google-github-actions/setup-gcloud@v0.2.0
-      with:
-        project_id: ${{ secrets.GCP_PROJECT_ID }}
-        service_account_key: ${{ secrets.GCP_SA_KEY }}
-        export_default_credentials: true
 
     - name: Build Docker Image
       run: docker compose build
@@ -80,4 +90,6 @@ jobs:
 
     - name: Clean up
       if: always()
-      run: rm -f .secrets
+      run: |
+        rm -f .secrets
+        rm -f /tmp/gcp-key.json
