attempting persistent logs

diff --git a/.github/workflows/deploy_frontend.yml b/.github/workflows/deploy_frontend.yml
--- a/.github/workflows/deploy_frontend.yml
+++ b/.github/workflows/deploy_frontend.yml
@@ -27,7 +27,7 @@ jobs:
     #   env:
     #     REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
     #   run: |
-    #     env 
+    #     #env 
     #     echo -e "\e[31mREACT_APP_API_URL=${REACT_APP_API_URL}\e[0m"
     #     exit 1
 
@@ -58,10 +58,11 @@ jobs:
         REACT_APP_ENVIRONMENT: ${{ env.REACT_APP_ENVIRONMENT }}
       run: |
         cd frontend
+        mkdir -p build_logs
+        TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
         export REACT_APP_BUILD_TIME=$(TZ=America/Argentina/Buenos_Aires date +"%Y-%m-%d %H:%M:%S")
         echo -e "\e[31mBuilding with environment variables:\e[0m"
-        env
-        # npm run build || (echo -e "\e[31mBuild step failed.\e[0m" && exit 1)
+        npm run build --verbose > build_logs/build_stdout_${TIMESTAMP}.log 2> build_logs/build_stderr_${TIMESTAMP}.log || (echo -e "\e[31mBuild step failed.\e[0m" && exit 1)
         echo -e "\e[32mBuild completed. Checking build output:\e[0m"
         # grep -r REACT_APP build || echo "No REACT_APP variables found in build output"
 
