no fucking idea

diff --git a/.github/workflows/deploy_frontend.yml b/.github/workflows/deploy_frontend.yml
--- a/.github/workflows/deploy_frontend.yml
+++ b/.github/workflows/deploy_frontend.yml
@@ -26,13 +26,6 @@ jobs:
       with:
         node-version: '20'
 
-    - name: Install dependencies
-      shell: bash
-      run: |
-        set -e
-        cd frontend
-        npm ci
-
     - name: Print Environment Variables and Secrets
       shell: bash
       run: |
@@ -41,29 +34,43 @@ jobs:
         # Uncomment the following line to print GITHUB_TOKEN (not recommended)
         # printf "\033[31mGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}\033[0m\n"
 
+    - name: Install dependencies
+      shell: bash
+      run: |
+        cd frontend
+        if ! npm ci; then
+          printf "\033[31mInstall dependencies step failed.\033[0m\n"
+          exit 1
+        fi
+
     - name: Build
       shell: bash
       env:
         REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
         REACT_APP_ENVIRONMENT: ${{ secrets.REACT_APP_ENVIRONMENT }}
       run: |
-        set -e
         cd frontend
-        npm run build
+        if ! npm run build; then
+          printf "\033[31mBuild step failed.\033[0m\n"
+          exit 1
+        fi
 
     - name: Setup Pages
       uses: actions/configure-pages@v4
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
+      continue-on-error: true
 
     - name: Upload artifact
       uses: actions/upload-pages-artifact@v3
       with:
         path: './frontend/build'
+      continue-on-error: true
 
     - name: Deploy to GitHub Pages
       id: deployment
       uses: actions/deploy-pages@v4
+      continue-on-error: true
 
     # This step runs when any previous step fails
     - name: Build Failed
@@ -71,6 +78,7 @@ jobs:
       shell: bash
       run: |
         printf "\033[31mBuild failed.\033[0m\n"
+        exit 1
 
     # This step runs when all previous steps succeed
     - name: Build Succeeded
